export {
    faMagnifyingGlass, 
    faArrowAltDown,
    faArrowDown,
    faArrowUp,
    faTrashAlt,
    faChevronDown,
    faChevronUp,
    faClipboard,
    faBuilding,
    faUsers,
    faUserSecret,
    faEnvelope,
    faPlane,
    faHome,
    faEdit,
    faChevronLeft,
    faChevronRight,
    faCalculator,
    faTablets,
    faFolders,
    faFileCircleCheck,
    faBooks,
    faCircleCheck,
    faArrowRight,
    faCommentsQuestionCheck,
    faFileExcel,
    faChevronDoubleRight,
   
} from '@fortawesome/pro-light-svg-icons';