export {
    faUserSecret,
    faEye,
    faEyeSlash,
    faArrowDown,
    faArrowUp,
    faArrowAltCircleDown,
    faCaretDown,
    faCaretUp,
    faChevronLeft,
    faChevronRight,
    faSort,
    faTrash,
    faTrashAlt,
    faCircle,
    faPlus,
    faPencil,
    faXmark,
    faFileCheck,
    faChevronDoubleRight,
    faMemoCircleInfo,
    faUserGroup,
    faVideo,
    faClipboardList,
    faFlask,
    faKey
} from "@fortawesome/pro-solid-svg-icons";
